### ISSUE TITLE
MVP validation error

### ISSUE THREAD

**Issue by jhoughes** [tfenster/verified-bluesky#1]
I've got an issue that I believe is based on being a dual MVP, and the Technology Area info field being too many characters.

The error received is "An error occured: Second level title too long: Ver. MVPs: CDM - On-premises and Hybrid AKS, Container Management"

This is feeding from a Technology Area field of "PowerShell, On-premises and Hybrid AKS, Container Management"

The MVP profile in question is:
https://mvp.microsoft.com/en-US/mvp/profile/5c4347e0-f116-ee11-8f6e-000d3a1ad36b

On mobile without time to review the code, but wanted to submit the issue before I forgot.

**Comment by tfenster** [comment]
@jhoughes Thanks for reporting! A stupid bug on my side... Should now be fix, can you please try again?

**Comment by jhoughes** [comment]
Huzzah! 

"Successfully verified you!" 

Thanks for digging into the issue, and thanks for the fantastic tool. 

It's great to see a resurgence of community!

**Comment by tfenster** [comment]
@jhoughes Thanks for the feedback! And indeed great to see something that might work again :)
