### ISSUE TITLE
GH Stars link not working

### ISSUE THREAD

**Issue by potatoqualitee** [tfenster/verified-bluesky#14]
Bonjour, 
I enter this and it says 404

Tried:
potatoqualitee
https://stars.github.com/profiles/potatoqualitee
https://stars.github.com/profiles/potatoqualitee/

tried it with a slash too, no cigar

**Comment by potatoqualitee** [comment]
lol ignore me, i didnt read

**Comment by potatoqualitee** [comment]
nm, i did read and its still not working. maybe cached? i updated it after realizing my profile listed my old handle

An error occured: Link to social network with handle funbucket.dev not found for Github Star potatoqualitee
If you think this is a bug, please file an issue on [GitHub](https://github.com/tfenster/verified-bluesky/issues) or contact [the "host account"](https://bsky.app/profile/verifiedsky.bsky.social) on Bluesky.

**Comment by tfenster** [comment]
I entered the values you provided for debugging and it just worked

![image](https://github.com/user-attachments/assets/7ed6c184-813a-4d5a-ab93-e42037d07964)

As you said, probably something was still cached somewhere for the GitHub Star profile. But it now worked, you are in :) Thanks for using it!
