### ISSUE TITLE
REQ: Be able to verify a regular Github account

### ISSUE THREAD

**Issue by unixorn** [tfenster/verified-bluesky#16]
It would be nice if mere mortal github accounts could be verified too :-)

**Comment by tfenster** [comment]
Hm, I would prefer to have something on the other side that needs some kind of independent confirmation. You can just set up a Bluesky profile and a GitHub account without anyone else doing anything, which is a bit thin for my taste. But I'll keep this open, maybe others agree and then I might look into it again

**Comment by tfenster** [comment]
Yes, but that doesn't really verify anything as there is no control on either side. I could easily get a bluesky account and a github account in the same name, but that doesn't proof anything as there is no external party involved

**Comment by unixorn** [comment]
I was thinking it would be nice to be able to confirm that bsky account XYZ makes official announcements for GitHub project ABC, but I guess all the verification you need for that is putting it in `readme.md`.

**Comment by tfenster** [comment]
Ah, now I see. That would make sense if it were individual labels like "github.com/abcd". But the label would be "GitHub user", so that wouldn't add a lot of information

**Comment by unixorn** [comment]
Good point, closing.
