### ISSUE TITLE
Error when adding Cloud Security category MVP

### ISSUE THREAD

**Issue by karlgots** [tfenster/verified-bluesky#2]
Hi, I get the following error when adding my [profile](https://mvp.microsoft.com/en-US/mvp/profile/9494271a-a004-e811-8104-3863bb2bca60).

An error occured: Second level title too long: Ver. MVPs: Security - Cloud Security (Microsoft Defender for Cloud, Azure network security products, GitHub Advanced Security)

**Comment by tfenster** [comment]
@karlgots Sorry, mistake on my side. Can you please try again? Should now be fixed
