### ISSUE TITLE
LinkedIn Verification

### ISSUE THREAD

**Issue by Tanddant** [tfenster/verified-bluesky#21]
LinkedIn offers the option to have verification with your government ID [check my profile for an example](https://www.linkedin.com/in/dan-toft/overlay/about-this-profile/)  - while not perfect, this would be a great "proxy way" to verify that people are who they say they are.

And if it's possible to "hijack" the LinkedIn verified status, then you wouldn't have to ever handle Government IDs which seems like a nightmare in and off itself

**Comment by tfenster** [comment]
I will definitely never ever handle gov IDs, way too much can go wrong there. And unfortunately AFAIK, LinkedIn doesn't have an API, so also no way for me to check
